/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import simpleFactory.car.CarMain;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        CarMain carMain = new CarMain();
        carMain.run();
    }
}
